"""
杨振宇老师完整论著清单（结构化数据）
=====================================
数据来源：核查记录/complete_publication_list.md（逐条经 API 核验，已排除同名研究者）
    ★ 第一作者 ｜ ☆ 通讯/末位 ｜ ○ 合作者
"""

JOURNAL_PAPERS = [
    dict(year='2020', kind='期刊论文', title='Digital phantoms for characterizing inconsistencies among radiomics extraction toolboxes', journal='Biomedical Physics & Engineering Express', cite='6(2):025016', doi='10.1088/2057-1976/ab779c', position='第 6/7 作者 ○合作者', authors='Chang Y; Lafata K; Wang C; Duan X; Geng R; **Yang Z**; Yin FF', evidence='Duke/DKU 放射组学工具箱一致性研究，合作者 Lafata、Chunhao Wang、Yin Fang-Fang；Crossref 记录含 Duke Kunshan 机构'),
    dict(year='2022', kind='期刊论文', title='A radiomics-boosted deep-learning model for COVID-19 and non-COVID-19 pneumonia classification using chest x-ray images', journal='Medical Physics', cite='49(5):3213–3222', doi='10.1002/mp.15582', position='第 2/5 作者 ○合作者', authors='Hu Z; **Yang Z**; Lafata KJ; Yin FF; Wang C', evidence='Duke 放疗系，与 Chunhao Wang / Yin Fang-Fang 合作；ORCID 自列；通讯作者 Chunhao Wang'),
    dict(year='2022', kind='期刊论文', title='Quantification of lung function on CT images based on pulmonary radiomic filtering', journal='Medical Physics', cite='49(11):7278–7286', doi='10.1002/mp.15837', position='第 1/7 作者 ★第一作者', authors='**Yang Z**; Lafata KJ; Chen X; Bowsher J; Chang Y; Wang C; Yin FF', evidence='Duke/DKU 肺功能影像组学；ORCID 自列第一作者；跨库（Europe PMC/OpenAlex/Crossref）一致'),
    dict(year='2022', kind='期刊论文', title='A personalized DVH prediction model for HDR brachytherapy in cervical cancer treatment', journal='Frontiers in Oncology', cite='12:967436', doi='10.3389/fonc.2022.967436', position='第 3/7 作者 ○合作者', authors='Li Z; Chen K; **Yang Z**; Zhu Q; Yang X; Li Z; Fu J', evidence='Europe PMC 全作者机构明确标注 Yang Z 为 "Duke University, Durham, NC, USA"；与上海六院 Zhen Li/Jie Fu 组合作'),
    dict(year='2023', kind='期刊论文', title='A neural ordinary differential equation model for visualizing deep neural network behaviors in multi-parametric MRI-based glioma segmentation', journal='Medical Physics', cite='50(8):4825–4838', doi='10.1002/mp.16286', position='第 1/8 作者 ★第一作者', authors='**Yang Z**; Hu Z; Ji H; Lafata K; Vaios E; Floyd S; Yin FF; Wang C', evidence='Duke 放疗系 + DKU；合作者 Vaios/Floyd/Lafata/Yin/Wang 全部为 Duke 放疗；arXiv:2203.00628 同作者'),
    dict(year='2023', kind='期刊论文', title='Development of a multi-feature-combined model: proof-of-concept with application to local failure prediction of post-SBRT or surgery early-stage NSCLC patients', journal='Frontiers in Oncology', cite='13:1185771', doi='10.3389/fonc.2023.1185771', position='第 1/9 作者 ★第一作者', authors='**Yang Z**; Wang C; Wang Y; Lafata KJ; Zhang H; Ackerson BG; Kelsey C; Tong B; Yin FF', evidence='Duke 放疗系肺癌 SBRT 队列（Kelsey/Tong 为 Duke 临床医师）；ORCID 自列'),
    dict(year='2023', kind='期刊论文', title='Deep learning-based dose map prediction for high-dose-rate brachytherapy', journal='Physics in Medicine & Biology', cite='68(17):175015', doi='10.1088/1361-6560/acecd2', position='第 2/8 作者 ○合作者', authors='Li Z; **Yang Z**; Lu J; Zhu Q; Wang Y; Zhao M; Li Z; Fu J', evidence='Europe PMC 机构字段明确为 "Yang Z — Duke University, Durham, NC, USA"；与上文上海六院组同一合作群（⚠ 见存疑条目）'),
    dict(year='2023', kind='期刊论文', title='A radiomics-incorporated deep ensemble learning model for multi-parametric MRI-based glioma segmentation', journal='Physics in Medicine & Biology', cite='68(18):185025', doi='10.1088/1361-6560/acf10d', position='第 2/7 作者 ○合作者', authors='Chen Y; **Yang Z**; Zhao J; Adamson J; Sheng Y; Yin FF; Wang C', evidence='Duke 放疗系（Adamson/Sheng/Yin/Wang 均为 Duke）；OpenAlex 机构含 Duke Kunshan'),
    dict(year='2024', kind='期刊论文', title='Quantifying U-Net uncertainty in multi-parametric MRI-based glioma segmentation by spherical image projection', journal='Medical Physics', cite='51(3):1931–1943', doi='10.1002/mp.16695', position='第 1/7 作者 ★第一作者', authors='**Yang Z**; Lafata K; Vaios E; Hu Z; Mullikin T; Yin FF; Wang C', evidence='Duke 放疗系；ORCID 自列；arXiv:2210.06512 同作者'),
    dict(year='2024', kind='期刊论文', title='Dose-Incorporated Deep Ensemble Learning for Improving Brain Metastasis Stereotactic Radiosurgery Outcome Prediction', journal='International Journal of Radiation Oncology·Biology·Physics', cite='120(2):603–613', doi='10.1016/j.ijrobp.2024.04.006', position='第 4/12 作者 ○合作者', authors='Zhao J; Vaios E; Wang Y; **Yang Z**; Cui Y; Reitman ZJ; Lafata KJ; Fecci P; Kirkpatrick J; Yin FF; Floyd S; Wang C', evidence='Duke 放疗/神经外科脑转移 SRS 队列；合作者 Reitman/Fecci/Kirkpatrick 均为 Duke'),
    dict(year='2024', kind='期刊论文', title='Prognostic value of different discretization parameters in ¹⁸FDG positron emission tomography radiomics of oropharyngeal squamous cell carcinoma', journal='Journal of Medical Imaging', cite='11(2):024007', doi='10.1117/1.JMI.11.2.024007', position='第 4/9 作者 ○合作者', authors='Riley BA; Stevens JB; Li X; **Yang Z**; Wang C; Mowery YM; Brizel DM; Yin FF; Lafata KJ', evidence='Duke 放疗系头颈癌 PET 影像组学；合作者 Mowery/Brizel/Yin/Lafata 均为 Duke'),
    dict(year='2024', kind='期刊论文', title='A dual-radiomics model for overall survival prediction in early-stage NSCLC patient using pre-treatment CT images', journal='Frontiers in Oncology', cite='14:1419621', doi='10.3389/fonc.2024.1419621', position='第 10/10 作者 ☆通讯/末位', authors='Zhang R; Zhu H; Chen M; Sang W; Lu K; Li Z; Wang C; Zhang L; Yin FF; **Yang Z**', evidence='末位通讯作者，DKU 医学物理研究生（Zhang Rihui 为其学生）；Yin Fang-Fang/Chunhao Wang 合作'),
    dict(year='2025', kind='期刊论文', title='Radiogenomic explainable AI with neural ordinary differential equation for identifying post-SRS brain metastasis radionecrosis', journal='Medical Physics', cite='52(4):2661–2674', doi='10.1002/mp.17635', position='第 3/12 作者 ○合作者', authors='Zhao J; Vaios E; **Yang Z**; Lu K; Floyd S; Yang D; Ji H; Reitman ZJ; Lafata KJ; Fecci P; Kirkpatrick JP; Wang C', evidence='Duke 放疗系放射基因组学；OpenAlex 机构含 Duke Kunshan'),
    dict(year='2025', kind='期刊论文', title='Total brain dose estimation in single-isocenter-multiple-targets (SIMT) radiosurgery via a novel deep neural network with spherical convolutions', journal='Medical Physics', cite='52(6):4266–4277', doi='10.1002/mp.17748', position='第 1/9 作者 ★第一作者', authors='**Yang Z**; Khazaieli M; Vaios E; Zhang R; Zhao J; Mullikin T; Yang A; Yin FF; Wang C', evidence='Duke/DKU SIMT 放疗；ORCID/Europe PMC/Crossref 一致；合作者 Mullikin/Vaios 为 Duke'),
    dict(year='2025', kind='期刊论文', title='Uncertainty quantification in multi-parametric MRI-based meningioma radiotherapy target segmentation', journal='Frontiers in Oncology', cite='15:1474590', doi='10.3389/fonc.2025.1474590', position='第 2/11 作者 ○合作者', authors='Wang L; **Yang Z**; LaBella D; Reitman Z; Ginn J; Zhao J; Adamson J; Lafata K; Calabrese E; Kirkpatrick J; Wang C', evidence='Duke 放疗系脑膜瘤靶区分割；合作者 Calabrese/Ginn/Adamson 均为 Duke'),
    dict(year='2025', kind='期刊论文', title='A Radiogenomic Deep Ensemble Learning Model for Identifying Radionecrosis Following Brain Metastases (BM) Stereotactic Radiosurgery in Patients With Non-small Cell Lung Cancer BM', journal='Advances in Radiation Oncology', cite='10(8):101826', doi='10.1016/j.adro.2025.101826', position='第 4/13 作者 ○合作者', authors='Zhao J; Vaios E; Calabrese E; **Yang Z**; Robertson S; Ginn J; Lu K; Yin FF; Reitman Z; Kirkpatrick J; Floyd S; Fecci P; Wang C', evidence='Duke 放疗系；OpenAlex 机构含 Duke Kunshan'),
    dict(year='2025', kind='期刊论文', title='An Implicit Registration Framework Integrating Kolmogorov-Arnold Networks with Velocity Regularization for Image-Guided Radiation Therapy', journal='Bioengineering (Basel)', cite='12(9):1005', doi='10.3390/bioengineering12091005', position='第 3/5 作者 ○合作者', authors='Sun P; Zhang C; **Yang Z**; Yin FF; Liu M', evidence='DKU 医学物理（Manju Liu 为 DKU 教授）；Yin Fang-Fang 合著'),
    dict(year='2025', kind='期刊论文', title='揭开医学图像分析算法的黑箱：医学图像分析中可解释人工智能的最新进展 / Uncovering the black box of medical image analysis algorithms: recent advances in explainable AI in medical image analysis', journal='科学通报 Chinese Science Bulletin', cite='70(33):5675–5695', doi='10.1360/tb-2024-1299', position='第 1/6 作者 ★第一作者', authors='**Yang Z**; Zhang R; Zhang L; Liu M; Duan X; Yin FF', evidence='中文综述，第一作者；机构为昆山杜克大学医学物理研究生项目；Crossref 卷期页 70(33):5675-5695 已核验'),
    dict(year='2026', kind='期刊论文', title='An exploratory study on integrating radiomics with vision transformers for enhancing medical imaging classification accuracy', journal='Medical Physics', cite='53(1):e70246', doi='10.1002/mp.70246', position='第 1/8 作者 ★第一作者', authors='**Yang Z**; Zhang R; Zhu H; Zhang H; Wang J; Chen M; Yin FF; Wang C', evidence='Duke/DKU；ORCID 自列；Europe PMC 2026 收录'),
    dict(year='2026', kind='期刊论文', title='A voxel-wise uncertainty-guided framework for glioma segmentation using spherical projection-based U-Net and localized refinement', journal='Medical Physics', cite='53(3):e70360', doi='10.1002/mp.70360', position='第 1/6 作者 ★第一作者', authors='**Yang Z**; Yang C; Zhang R; Wang C; Chen M; Yin FF', evidence='Duke/DKU；Europe PMC 2026 收录；arXiv:2507.15622 同作者'),
    dict(year='2026', kind='期刊论文', title='PhysMorph: A biomechanical and image-guided deep learning framework for real-time multi-modal liver image registration', journal='Physics and Imaging in Radiation Oncology', cite='37:100906', doi='10.1016/j.phro.2026.100906', position='第 8/8 作者 ☆通讯/末位', authors='Zhang Z; Guo D; Lu K; Jiang Z; Zhong H; Yin FF; Ren L; **Yang Z**', evidence='末位通讯作者；合作者 Yin Fang-Fang（Duke 放疗）、Lei Ren（Duke）；DKU 医学物理课题组'),
    dict(year='2026', kind='期刊论文', title='Knowledge-based deep residual U-Net (DRU) for synthetic CT generation using a single MR volume for frameless radiosurgery', journal='Journal of Applied Clinical Medical Physics', cite='27(1):e70343', doi='10.1002/acm2.70343', position='第 6/9 作者 ○合作者', authors='Shu X; Lu K; Zhao J; Ginn J; Kim Y; **Yang Z**; Adamson J; Mullikin T; Wang C', evidence='Duke 放疗系；合作者 Adamson/Mullikin/Ginn/Kim 均为 Duke 放疗物理师'),
    dict(year='2026', kind='期刊论文', title='An Explainable Deep Model for Risk Scoring and Accurate Radionecrosis Identification Following Brain Metastasis Stereotactic Radiosurgery', journal='International Journal of Radiation Oncology·Biology·Physics', cite='125(2):649–659', doi='10.1016/j.ijrobp.2025.11.038', position='第 4/12 作者 ○合作者', authors='Zhao J; Vaios E; Calabrese E; **Yang Z**; Ginn J; Gonzalez A; Floyd S; Reitman ZJ; Fecci P; Kirkpatrick J; Lafata KJ; Wang C', evidence='Duke 放疗/神经外科；Europe PMC 2026 收录；同一工作的 ASTRO 摘要见 B 区'),
    dict(year='2026', kind='期刊论文', title='Integrating Swin Transformers and Wavelet CNNs for Hierarchical Global–Local Mammographic Image Analysis', journal='IEEE Transactions on Radiation and Plasma Medical Sciences', cite='早期访问（pp.1–1）', doi='10.1109/TRPMS.2026.3724585', position='第 8/8 作者 ☆通讯/末位', authors='Dai X; Zhang C; Zhang R; Shi K; Chen M; Wang J; Yin FF; **Yang Z**', evidence='Crossref ORCID 过滤唯一命中项，Yang Z 机构明确为 "Duke Kunshan University, Medical Physics Graduate Program"；末位通讯'),
]

CONFERENCE_ABSTRACTS = [
    dict(year='2021', kind='会议摘要', title='Association Between Dosiomics-Based Index with Radiation Pneumonitis Induced by Radiation Therapy of Breast Cancers', journal='Medical Physics（AAPM 2021 年会摘要）', cite='48(6)', doi='—', position='第 1/5 作者 ★第一作者', authors='**Yang Z**; Chen X; Chen M; Wang C; Yin F', evidence='Scholars@Duke 出版记录 pid 1495133，NLM 引用格式列出完整作者，Yang Z 居首；DKU/Duke 剂量组学'),
    dict(year='2022', kind='会议摘要', title='A Comparative Study of Radiomics and Deep-Learning Approaches for Predicting Surgery Outcomes in Early-Stage Non-Small Cell Lung Cancer (NSCLC)', journal='Medical Physics（AAPM 2022 年会摘要）', cite='49(6):E196', doi='—', position='第 2/8 作者 ○合作者', authors='Zhang H; **Yang Z**; Ackerson B; Hu Z; Khazaieli M; Kelsey C; Yin F; Wang C', evidence='Scholars@Duke pid 1817655；Duke 放疗系肺癌队列（Kelsey 为 Duke 胸放医师）'),
    dict(year='2022', kind='会议摘要', title='A Deep Learning Model with Radiomics Analysis Integration for Glioblastoma Post-Resection Survival Prediction', journal='Medical Physics（AAPM 2022 年会摘要）', cite='49(6):E364', doi='—', position='第 2/8 作者 ○合作者', authors='Hu Z; **Yang Z**; Zhao J; Zhang H; Vaios E; Lafata K; Yin F; Wang C', evidence='Scholars@Duke pid 1526963（WOS:000808579201118）；Duke 放疗系；全文见 arXiv:2203.05891'),
    dict(year='2022', kind='会议摘要', title='A Radiomics-Integrated Deep-Learning Model for Identifying Radionecrosis Following Brain Metastasis Stereotactic Radiosurgery', journal='Medical Physics（AAPM 2022 年会摘要）', cite='49(6):E457', doi='—', position='第 2/9 作者 ○合作者', authors='Zhao J; **Yang Z**; Hu Z; Vaios E; Carpenter D; Floyd S; Lafata K; Yin F; Wang C', evidence='Scholars@Duke pid 1526961；Duke 放疗系脑转移放射性坏死'),
    dict(year='2022', kind='会议摘要', title='Effect of PET Image Discretization On Radiomic Features of Patients Undergoing Definitive Radiotherapy for Oropharyngeal Cancer', journal='Medical Physics（AAPM 2022 年会摘要）', cite='49(6):E577–E578', doi='—', position='第 3/7 作者 ○合作者', authors='Riley B; Wang C; **Yang Z**; Mowery Y; Brizel D; Yin F; Lafata K', evidence='Scholars@Duke pid 1526965；Duke 头颈癌 PET 影像组学'),
    dict(year='2022', kind='会议摘要', title='A Radiomics-Integrated Deep Learning Model for Identifying Radionecrosis Following Brain Metastasis Stereotactic Radiosurgery (SRS)', journal='International Journal of Radiation Oncology·Biology·Physics（ASTRO 2022）', cite='114(3):S114', doi='10.1016/j.ijrobp.2022.07.551', position='第 4/10 作者 ○合作者', authors='Zhao J; Vaios EJ; Carpenter DJ; **Yang Z**; Cui Y; Lafata K; Fecci P; Yin FF; Floyd SR; Wang C', evidence='Crossref 作者字段含 "Z. Yang"；Duke 放疗系（Vaios/Fecci/Floyd/Wang）'),
    dict(year='2023', kind='会议摘要', title='A Radiogenomic Machine Learning Model for Glioblastoma Post-Resection Overall Survival Group Prediction', journal='International Journal of Radiation Oncology·Biology·Physics（ASTRO 2023）', cite='117(2):S156', doi='10.1016/j.ijrobp.2023.06.580', position='第 3/7 作者 ○合作者', authors='Wang L; Vaios EJ; **Yang Z**; Zhao J; Yin FF; Reitman ZJ; Wang C', evidence='Crossref 作者字段含 "Z. Yang"；Duke 放疗系 + Reitman（Duke 神经肿瘤）'),
    dict(year='2024', kind='会议摘要', title='Radiogenomic Deep Ensemble Learning for Identifying Radionecrosis Following Brain Metastasis Stereotactic Radiosurgery (SRS)', journal='International Journal of Radiation Oncology·Biology·Physics（ASTRO 2024）', cite='120(2):S101', doi='10.1016/j.ijrobp.2024.07.183', position='第 3/12 作者 ○合作者', authors='Zhao J; Vaios EJ; **Yang Z**; Robertson SH; Ginn J; Lu K; Yin FF; Reitman ZJ; Kirkpatrick JP; Floyd SR; Fecci P; Wang C', evidence='Crossref 作者字段含 "Z. Yang"；Duke 放疗系；Scholars@Duke pid 1659580 一致'),
    dict(year='2024', kind='会议摘要', title='A Radiomics-Embedded Vision Transformer for Medical Image Recognition Efficiency Improvement', journal='Medical Physics（会议摘要，2024 年 9 月期）', cite='51(9):6595', doi='—', position='第 9/9 作者 ☆通讯/末位', authors='Zhu H; Wang C; Zhang R; Liu M; Guo D; Zhao H; Chen M; Yin FF; **Yang Z**', evidence='Scholars@Duke pid 1669586，NLM 完整作者列表末位为 Yang Z；DKU 医学物理课题组'),
    dict(year='2024', kind='会议摘要', title='Quantifying U-Net Uncertainty in MRI-Based Meningioma Segmentation for Radiotherapy', journal='Medical Physics（会议摘要，2024 年 9 月期）', cite='51(9):6600', doi='—', position='第 2/10 作者 ○合作者', authors='Wang L; **Yang Z**; LaBella D; Reitman ZJ; Ginn J; Adamson J; Lafata K; Calabrese E; Wang C; Zhao J', evidence='Scholars@Duke pid 1669818；Duke 放疗系脑膜瘤分割'),
    dict(year='2024', kind='会议摘要', title='A Dual-Radiomics Combined Model for Overall Survival Prediction in Early-Stage NSCLC Patients Using Pre-Treatment CT Images', journal='Medical Physics（会议摘要，2024 年 9 月期）', cite='51(9):6616', doi='—', position='第 9/9 作者 ☆通讯/末位', authors='Zhang R; Zhu H; Li Z; Sang W; Lu K; Wang C; Zhang L; Yin FF; **Yang Z**', evidence='Scholars@Duke pid 1669519；对应期刊论文见 A 区（Front Oncol 2024）'),
    dict(year='2024', kind='会议摘要', title='An Explainable Neural Radiomic Sequence Model with Spatiotemporal Continuity for Quantifying 4DCT-Based Pulmonary Ventilation', journal='Medical Physics（会议摘要，2024 年 10 月期）', cite='51(10):7652', doi='—', position='第 7/7 作者 ☆通讯/末位', authors='Zhang R; Zhu H; Zhao J; Zhang L; Yin FF; Wang C; **Yang Z**', evidence='Scholars@Duke pid 1662377；末位通讯；全文见 arXiv:2503.23898'),
    dict(year='2025', kind='会议摘要', title='An Explainable Deep Model for Risk Scoring and Accurate Radionecrosis Identification Following Brain Metastasis Stereotactic Radiosurgery', journal='International Journal of Radiation Oncology·Biology·Physics（ASTRO 2025）', cite='123(1):S154', doi='10.1016/j.ijrobp.2025.06.1247', position='第 4/10 作者 ○合作者', authors='Zhao J; Vaios EJ; Calabrese E; **Yang Z**; Ginn J; Floyd SR; Reitman ZJ; Fecci P; Lafata K; Wang C', evidence='Crossref 作者字段含 "Z. Yang"；同一工作期刊全文见 A 区'),
    dict(year='2025', kind='会议摘要', title='Design and Evaluation of a Unified Machine Learning Model for Predicting Normal Brain Toxicity in Single-Isocenter-Multi-Target Stereotactic Radiosurgery', journal='International Journal of Radiation Oncology·Biology·Physics（ASTRO 2025）', cite='123(1):e48', doi='10.1016/j.ijrobp.2025.06.3383', position='第 6/9 作者 ○合作者', authors='Huang Z; Zhao J; Mullikin TC; Lu K; Ginn J; **Yang Z**; Xie Y; Kim Y; Wang C', evidence='Crossref 作者字段含 "Z. Yang"；OpenAlex 机构含 Duke Kunshan；Duke 放疗系 SIMT'),
    dict(year='2025', kind='会议摘要', title='Spherical Slicing and Convolutions for Accurate Glioma Tumor Segmentation Using Multi-Parametric MRI', journal='Medical Physics（会议摘要，2025 年 10 月期）', cite='52(10)', doi='—', position='第 10/10 作者 ☆通讯/末位', authors='Zhang R; Zhu H; Zhang C; Xia R; Zhao J; Lu K; Zhang L; Wang C; Yin FF; **Yang Z**', evidence='Scholars@Duke pid 1708467，NLM 完整作者列表末位为 Yang Z；DKU 医学物理'),
    dict(year='2025', kind='会议摘要', title='Improving Mammography Diagnosis Accuracy through Global Context and Local Lesion Integration', journal='Medical Physics（会议摘要，2025 年 10 月期）', cite='52(10)', doi='—', position='第 9/9 作者 ☆通讯/末位', authors='Dai X; Zhang C; Duan X; Zhang R; Xia F; Chen M; Yin FF; Wang C; **Yang Z**', evidence='Scholars@Duke pid 1708470；末位通讯；对应期刊论文见 A 区（IEEE TRPMS 2026）'),
    dict(year='2025', kind='会议摘要', title='Enhancing CNN-Based Brain Metastasis Detection in MRI By Integrating Locoregional 3D Deformation Technique', journal='Medical Physics（会议摘要，2025 年 10 月期）', cite='52(10)', doi='—', position='第 8/8 作者 ☆通讯/末位', authors='Wu C; Shi K; Zhao J; Lu K; Chen M; Yin FF; Wang C; **Yang Z**', evidence='Scholars@Duke pid 1708576；末位通讯；DKU 医学物理硕士生第一作者'),
    dict(year='2025', kind='会议摘要', title='Predicting Brain V60% in Linac-Based Single-Isocenter-Multiple-Targets (SIMT) Stereotactic Radiosurgery Using Machine Learning', journal='Medical Physics（会议摘要，2025 年 10 月期）', cite='52(10)', doi='—', position='第 5/8 作者 ○合作者', authors='Huang Z; Zhao J; Lu K; Ginn J; **Yang Z**; Xie Y; Kim Y; Wang C', evidence='Scholars@Duke pid 1708579；Duke 放疗系 SIMT 计划质量'),
    dict(year='2025', kind='会议摘要', title='A Radiomic Quantification Framework for Hyperparameter Optimization in Texture Characterization', journal='Medical Physics（会议摘要，2025 年 10 月期）', cite='52(10)', doi='—', position='第 11/11 作者 ☆通讯/末位', authors='Zhang R; Zhu H; Qian C; Sang W; Xia F; Qian K; Ni C; Lu Y; Wang C; Yin FF; **Yang Z**', evidence='Scholars@Duke pid 1708721；末位通讯；DKU 影像组学纹理参数研究'),
    dict(year='2025', kind='会议摘要', title='Biologically Guided Deep Learning for MRI-Based Brain Metastasis Outcome Prediction after Stereotactic Radiosurgery', journal='Medical Physics（会议摘要，2025 年 10 月期）', cite='52(10)', doi='—', position='第 4/9 作者 ○合作者', authors='Zhao J; Vaios E; Calabrese E; **Yang Z**; Ji H; Wang L; Lee CY; Lafata KJ; Wang C', evidence='Scholars@Duke pid 1708900；Duke 放疗系脑转移 SRS'),
    dict(year='2025', kind='会议摘要', title='Combining Patch-Based CNN Models with Hierarchical Shapley Explanations for Breast Cancer Diagnosis', journal='Medical Physics（会议摘要，2025 年 10 月期）', cite='52(10)', doi='—', position='第 10/10 作者 ☆通讯/末位', authors='Shi K; Li Z; Wu C; Zhao J; Chen X; Wang J; Ginn J; Yin FF; Wang C; **Yang Z**', evidence='Scholars@Duke pid 1708963；末位通讯；DKU 医学物理可解释 AI'),
]

PREPRINTS = [
    dict(year='2021', kind='预印本', title='Quantification of lung function on CT images based on pulmonary radiomic filtering', journal='arXiv', cite='arXiv:2105.11171（v1 2021-05-24，v4 2022-06-24）', doi='10.48550/arXiv.2105.11171', position='第 1/7 作者 ★第一作者', authors='**Yang Z**; Lafata KJ; Chen X; Bowsher J; Chang Y; Wang C; Yin FF', evidence='arXiv API 返回；已正式发表（Med Phys 2022;49(11):7278-7286，见 A 区）'),
    dict(year='2021', kind='预印本', title='A Radiomics-Boosted Deep-Learning Model for COVID-19 and Non-COVID-19 Pneumonia Classification Using Chest X-ray Image', journal='arXiv', cite='arXiv:2107.08667（v1 2021-07-19，v2 2021-10-23）', doi='10.48550/arXiv.2107.08667', position='第 2/5 作者 ○合作者', authors='Hu Z; **Yang Z**; Lafata KJ; Yin FF; Wang C', evidence='arXiv API 返回；已正式发表（Med Phys 2022;49(5):3213-3222，见 A 区）'),
    dict(year='2022', kind='预印本', title='A Neural Ordinary Differential Equation Model for Visualizing Deep Neural Network Behaviors in Multi-Parametric MRI based Glioma Segmentation', journal='arXiv', cite='arXiv:2203.00628（v1 2022-03-01，v2 2022-03-23）', doi='10.48550/arXiv.2203.00628', position='第 1/7 作者 ★第一作者', authors='**Yang Z**; Hu Z; Ji H; Lafata K; Floyd S; Yin FF; Wang C', evidence='arXiv API 返回；已正式发表（Med Phys 2023;50(8):4825-4838，见 A 区）'),
    dict(year='2022', kind='预印本', title='A Deep Learning Model with Radiomics Analysis Integration for Glioblastoma Post-Resection Survival Prediction', journal='arXiv', cite='arXiv:2203.05891（2022-03-11）', doi='10.48550/arXiv.2203.05891', position='第 2/8 作者 ○合作者', authors='Hu Z; **Yang Z**; Zhang H; Vaios E; Lafata K; Yin FF; Wang C', evidence='arXiv API 返回；**至今未见期刊全文版**，仅对应 B 区 AAPM 2022 会议摘要'),
    dict(year='2022', kind='预印本', title='Quantifying U-Net Uncertainty in Multi-Parametric MRI-based Glioma Segmentation by Spherical Image Projection', journal='arXiv', cite='arXiv:2210.06512（v1 2022-10-12，v3 2023-08-13）', doi='10.48550/arXiv.2210.06512', position='第 1/7 作者 ★第一作者', authors='**Yang Z**; Lafata K; Vaios E; Hu Z; Mullikin T; Yin FF; Wang C', evidence='arXiv API 返回；已正式发表（Med Phys 2024;51(3):1931-1943，见 A 区）'),
    dict(year='2023', kind='预印本', title='A Radiomics-Incorporated Deep Ensemble Learning Model for Multi-Parametric MRI-based Glioma Segmentation', journal='arXiv', cite='arXiv:2303.10533（2023-03-19）', doi='10.48550/arXiv.2303.10533', position='第 2/7 作者 ○合作者', authors='Chen Y; **Yang Z**; Zhao J; Adamson J; Sheng Y; Yin FF; Wang C', evidence='arXiv API 返回；已正式发表（Phys Med Biol 2023;68(18):185025，见 A 区）'),
    dict(year='2024', kind='预印本', title='Single-Iso-Multiple-Targets (SIMT) Radiosurgery Plan Quality Control via a Novel Deep Neural Network with Spherical Convolutions', journal='Research Square', cite='预印本 v1', doi='10.21203/rs.3.rs-4488238/v1', position='第 1/9 作者 ★第一作者', authors='**Yang Z**; Khazaieli M; Vaios E; Zhang R; Zhao J; Mullikin T; Yang A; Yin FF; Wang C', evidence='Europe PMC（PPR 源）+ OpenAlex 收录；已正式发表（Med Phys 2025;52(6):4266-4277，见 A 区）'),
    dict(year='2025', kind='预印本', title='Synthetic Poisoning Attacks: The Impact of Poisoned MRI Image on U-Net Brain Tumor Segmentation', journal='arXiv', cite='arXiv:2502.03825（2025-02-06）', doi='10.48550/arXiv.2502.03825', position='第 9/9 作者 ☆通讯/末位', authors='Li T; Zeng T; Zheng Y; Zhang C; Lu J; Huang H; Chu C; Yin FF; **Yang Z**', evidence='arXiv API 返回（au:"Zhenyu Yang" 检索命中）；末位通讯，Yin Fang-Fang 合著，DKU/Duke 医学物理'),
    dict(year='2025', kind='预印本', title='An Explainable Neural Radiomic Sequence Model with Spatiotemporal Continuity for Quantifying 4DCT-based Pulmonary Ventilation', journal='arXiv', cite='arXiv:2503.23898（v1 2025-03-31，v2 2025-07-20）', doi='10.48550/arXiv.2503.23898', position='第 7/7 作者 ☆通讯/末位', authors='Zhang R; Zhu H; Zhao J; Zhang L; Yin FF; Wang C; **Yang Z**', evidence='arXiv API 返回；**至今未见期刊全文版**，仅对应 B 区 2024 年会议摘要'),
    dict(year='2025', kind='预印本', title='Embedding Radiomics into Vision Transformers for Multimodal Medical Image Classification', journal='arXiv', cite='arXiv:2504.10916（v1 2025-04-15，v2 2025-04-23）', doi='10.48550/arXiv.2504.10916', position='第 1/8 作者 ★第一作者', authors='**Yang Z**; Zhu H; Zhang R; Zhang H; Wang J; Wang C; Chen M; Yin FF', evidence='arXiv API 返回；已正式发表（Med Phys 2026;53(1):e70246，见 A 区）'),
    dict(year='2025', kind='预印本', title='A Voxel-Wise Uncertainty-Guided Framework for Glioma Segmentation Using Spherical Projection-Based U-Net and Localized Refinement in Multi-Parametric MRI', journal='arXiv', cite='arXiv:2507.15622（2025-07-21）', doi='10.48550/arXiv.2507.15622', position='第 1/6 作者 ★第一作者', authors='**Yang Z**; Yang C; Zhang R; Chen M; Wang C; Yin FF', evidence='arXiv API 返回；已正式发表（Med Phys 2026;53(3):e70360，见 A 区）'),
    dict(year='2025', kind='预印本', title='A Dual Radiomic and Dosiomic Filtering Technique for Locoregional Radiation Pneumonitis Prediction in Breast Cancer Patients', journal='arXiv', cite='arXiv:2508.02169（2025-08-04）', doi='10.48550/arXiv.2508.02169', position='第 1/11 作者 ★第一作者', authors='**Yang Z**; Chen Q; Zhang R; Liu M; Guo F; Yang M; Tang M; Zhou L; Wang C; Chen M; Yin FF', evidence='arXiv API 返回；**至今未见期刊全文版**（Crossref/Europe PMC 检索无对应期刊记录）'),
]

THESES_AND_PROJECTS = [
    dict(year='2020', kind='学位论文', title='Development of a Voxel-Based Radiomics Calculation Platform for Medical Image Analysis（硕士论文）', journal='Duke Kunshan University / Duke University（DukeSpace 机构库）', cite='—', doi='hdl:10161/20784', position='唯一作者 ★', authors='**Yang Z**', evidence="DukeSpace REST API 检索：`dc.contributor.author = Yang, Zhenyu`，`dc.contributor.advisor = Yin, Fang-Fang`，类型 Master's thesis；与其 DKU 医学物理硕士学历一致"),
    dict(year='2023', kind='学位论文', title='Explainable Artificial Intelligence Techniques in Medical Imaging Analysis（博士论文）', journal='Duke University（DukeSpace 机构库）', cite='—', doi='hdl:10161/27597', position='唯一作者 ★', authors='**Yang Z**', evidence='DukeSpace REST API 检索：`dc.contributor.author = Yang, Zhenyu`，`dc.contributor.advisor = Yin, Fang-Fang`，类型 Dissertation；Scholars@Duke 学历栏亦记 Duke University 2023 Ph.D.'),
    dict(year='2024', kind='科研项目', title='放疗中腹部图像自动分割的不确定性量化与评估研究（国家自然科学基金 **青年科学基金项目**）', journal='国家自然科学基金委员会（NSFC）2024 年度', cite='—', doi='—', position='项目负责人 ★', authors='**杨振宇**（PI）', evidence='昆山杜克大学官方新闻（中英文双语）明确列名 "Dr. Zhenyu Yang, Research Assistant Professor of Medical Physics" 获 NSFC 青年科学基金项目资助'),
]

EARLY_PHYSICS = [
    dict(year='2019', kind='期刊论文', title='Thermodynamic analysis of a long-range interacting spin system', journal='Modern Physics Letters B', cite='33(7):1950072', doi='10.1142/S0217984919500726', position='第 1/2 作者 ★第一作者', authors='**Yang Z**; Hou JX', evidence='ORCID 自列 + Crossref 核验；合作者侯吉旋（东南大学物理学院）；OpenAlex 机构含 Duke Kunshan / Southeast University'),
    dict(year='2019', kind='期刊论文', title='Thermodynamic properties of a long-range interacting Bose system in staggered magnetic field', journal='The European Physical Journal B', cite='92(8):170', doi='10.1140/epjb/e2019-100099-2', position='第 1/2 作者 ★第一作者', authors='**Yang Z**; Hou JX', evidence='ORCID 自列 + Crossref 核验（article-number 170）；侯吉旋合作'),
    dict(year='2019', kind='期刊论文', title="Calculating the ground state energy of hydrogen molecules and helium hydride ions using Bohr's quantum theory", journal='European Journal of Physics', cite='40(6):065405', doi='10.1088/1361-6404/ab32ce', position='第 1/2 作者 ★第一作者', authors='**Yang Z**; Hou JX', evidence='ORCID 自列 + Crossref 核验；侯吉旋合作'),
    dict(year='2020', kind='期刊论文', title='Shape transformation of red blood cells induced by the osmotic pressure', journal='European Journal of Physics', cite='41(6):065501', doi='10.1088/1361-6404/aba568', position='第 1/2 作者 ★第一作者', authors='**Yang Z**; Hou JX', evidence='ORCID 自列 + Crossref 核验；侯吉旋合作'),
    dict(year='2020', kind='期刊论文', title='Non-Markovian Mpemba effect in mean-field systems', journal='Physical Review E', cite='101(5):052106', doi='10.1103/PhysRevE.101.052106', position='第 1/2 作者 ★第一作者', authors='**Yang Z**（署 Zhen-Yu Yang）; Hou JX', evidence='ORCID 自列 + Crossref 核验；侯吉旋合作'),
    dict(year='2022', kind='期刊论文', title='Mpemba effect of a mean-field system: The phase transition time', journal='Physical Review E', cite='105(1):014119', doi='10.1103/PhysRevE.105.014119', position='第 1/2 作者 ★第一作者', authors='**Yang Z**（署 Zhen-Yu Yang）; Hou JX', evidence='ORCID 自列 + Crossref 核验；侯吉旋合作；DKU 官方新闻提及其发表刊物包含 Physical Review E'),
]



AWARDS = [
    "AAPM 年会最佳论文摘要奖（Best Paper Abstract Award）",
    "放射外科学会（RSS）年会培训学员研究成就奖（Trainee Research Achievement Award）",
]


def all_items() -> list[dict]:
    """全部条目（带类别标签），按年份倒序。"""
    items = []
    for name, rows in [("期刊论文", JOURNAL_PAPERS), ("会议摘要", CONFERENCE_ABSTRACTS),
                       ("预印本", PREPRINTS), ("学位论文/项目", THESES_AND_PROJECTS),
                       ("早期物理研究", EARLY_PHYSICS)]:
        for r in rows:
            items.append({**r, "category": name})
    return sorted(items, key=lambda x: (-int(x["year"]), x["title"]))


def stats() -> dict:
    return {
        "期刊论文": len(JOURNAL_PAPERS),
        "会议摘要": len(CONFERENCE_ABSTRACTS),
        "预印本": len(PREPRINTS),
        "学位论文/项目": len(THESES_AND_PROJECTS),
        "早期物理研究": len(EARLY_PHYSICS),
        "合计": (len(JOURNAL_PAPERS) + len(CONFERENCE_ABSTRACTS) + len(PREPRINTS)
                 + len(THESES_AND_PROJECTS) + len(EARLY_PHYSICS)),
        "第一作者(★)": sum(1 for r in JOURNAL_PAPERS if "★" in r["position"]),
        "通讯末位(☆)": sum(1 for r in JOURNAL_PAPERS if "☆" in r["position"]),
    }
