"""
杨振宇老师文献数据库（仅收录可核实为其本人成果的条目）
=========================================================
已排除同名研究者（如杜克 BME Farsiu 实验室的另一位 Zhenyu Yang）。
位次标记：★ 第一作者 ｜ ☆ 通讯/末位（导师位）｜ ○ 合作者
"""
from __future__ import annotations

# 主题标签（用于筛选）
TOPICS = [
    "肺通气成像", "放射组学方法学", "不确定性量化", "分割",
    "预后预测", "生存分析", "放疗剂量学", "近距离治疗",
    "图像配准", "可解释AI", "影像基因组学", "合成CT",
    "深度学习架构", "早期物理研究",
]

# ----------------------------------------------------------------------
# 医学影像 / 医学物理
# ----------------------------------------------------------------------
PUBLICATIONS = [
    dict(year=2020, position="○", topic=["放射组学方法学", "可解释AI"],
         title="Digital phantoms for characterizing inconsistencies among radiomics extraction toolboxes",
         journal="Biomed Phys Eng Express", cite="2020;6(2):025016",
         doi="10.1088/2057-1976/ab779c", first_author="Chang Y",
         finding="三家工具箱算出的 61 个特征里，只有 45%–55% 完全一致（CCC=1）；差异来自数学定义、预处理与计算方法。",
         replicate="—（方法学基础，平台在「体素级放射组学滤波」页体现其思想）"),
    dict(year=2022, position="★", topic=["肺通气成像", "放射组学方法学"],
         title="Quantification of lung function on CT images based on pulmonary radiomic filtering",
         journal="Medical Physics", cite="2022;49(11):7278-7286",
         doi="10.1002/mp.15837", first_author="Yang Z",
         finding="15 mm 滑窗 + 53 个特征做体素级滤波；GLRLM-RunLengthNonUniformity 与 GLCOM-SumAverage 和 PET/SPECT 通气图相关性最高（ρ≈0.45–0.46），优于 HU 阈值法。",
         replicate="✅ 专栏 R1 / 页面「体素级放射组学滤波」"),
    dict(year=2022, position="○", topic=["深度学习架构"],
         title="A radiomics-boosted deep-learning model for COVID-19 and non-COVID-19 pneumonia classification using chest x-ray images",
         journal="Medical Physics", cite="2022;49(5):3213-3222",
         doi="10.1002/mp.15582", first_author="Hu Z",
         finding="用 2D 滑窗把放射组学特征做成特征图，用 VGG/DenseNet 的显著性图挑互补特征，图像+特征图联合训练；812 张胸片，50 次重复。",
         replicate="—（平台「影像实验室」可提取同族特征）"),
    dict(year=2022, position="○", topic=["放疗剂量学", "近距离治疗"],
         title="A personalized DVH prediction model for HDR brachytherapy in cervical cancer treatment",
         journal="Frontiers in Oncology", cite="2022;12:967436",
         doi="10.3389/fonc.2022.967436", first_author="Li Z†, Chen K†",
         finding="PCA + kNN 选相似病例 + KDE 建距离-剂量概率模型，预测膀胱/直肠 D2cc 等指标，绝对残差约 0.38–0.97 Gy。",
         replicate="✅ 专栏 R6 / 页面「放疗剂量学工具」"),
    dict(year=2022, position="○", topic=["生存分析", "深度学习架构"],
         title="A Deep Learning Model with Radiomics Analysis Integration for Glioblastoma Post-Resection Survival Prediction",
         journal="AAPM 年会摘要（Med Phys 2022;49(6):E364）；全文 arXiv:2203.05891",
         cite="arXiv:2203.05891", doi="", first_author="Hu Z",
         finding="235 例 GBM，456 个放射组学特征 + Models Genesis 深度特征 + 临床特征，SVM 融合；AUC 0.69（2D）/0.71（3D）。⚠️ 会议摘要，非正式期刊论文。",
         replicate="✅ 专栏 R4（三源融合同源方法）"),
    dict(year=2023, position="★", topic=["分割", "可解释AI", "深度学习架构"],
         title="A neural ordinary differential equation model for visualizing deep neural network behaviors in multi-parametric MRI-based glioma segmentation",
         journal="Medical Physics", cite="2023;50(8):4825-4838",
         doi="10.1002/mp.16286", first_author="Yang Z",
         finding="用 Neural ODE（RK4 + 伴随灵敏度法）把网络行为可视化；据此判断 T1ce 是 ET/TC 的关键序列、FLAIR+T2 是 WT 的关键序列。",
         replicate="—（需 GPU 训练，平台在「术语库」与文献解读中说明）"),
    dict(year=2023, position="★", topic=["预后预测", "分割"],
         title="Development of a multi-feature-combined model: proof-of-concept with application to local failure prediction of post-SBRT or surgery early-stage NSCLC patients",
         journal="Frontiers in Oncology", cite="2023;13:1185771",
         doi="10.3389/fonc.2023.1185771", first_author="Yang Z",
         finding="105 手工特征 + 512 维深度特征 + 4 项临床信息三源融合；AUC 0.742–0.825（手术）/0.888–0.920（SBRT），显著优于任何单一来源。",
         replicate="✅ 专栏 R4 / 页面「特征建模与预后」"),
    dict(year=2023, position="○", topic=["分割", "放射组学方法学"],
         title="A radiomics-incorporated deep ensemble learning model for multi-parametric MRI-based glioma segmentation",
         journal="Physics in Medicine & Biology", cite="2023;68(18):185025",
         doi="10.1088/1361-6560/acf10d", first_author="Chen Y",
         finding="56 个放射组学特征图经 PCA 取前 4 主成分，作为 4 个 U-Net 子模型的额外通道；4 组 softmax 叠加后用 Otsu 二值化。",
         replicate="✅ 专栏 R2（Otsu 聚合步骤）"),
    dict(year=2023, position="○", topic=["放疗剂量学", "近距离治疗"],
         title="Deep learning-based dose map prediction for high-dose-rate brachytherapy",
         journal="Physics in Medicine & Biology", cite="2023;68:175015",
         doi="10.1088/1361-6560/acecd2", first_author="Li Z",
         finding="从「预测 DVH 汇总指标」升级为直接预测三维剂量分布图。",
         replicate="✅ 专栏 R6（剂量图思想）"),
    dict(year=2023, position="★", topic=["可解释AI", "不确定性量化"],
         title="博士论文：Explainable Artificial Intelligence Techniques in Medical Imaging Analysis",
         journal="Duke University 博士论文", cite="142 页",
         doi="", first_author="Yang Z",
         finding="第1章为领域导论；第2章肺放射组学滤波；第3章 Neural ODE 可视化；第4章多特征融合预测局部失败。导师殷芳芳。",
         replicate="—（平台全部模块的方法论来源）"),
    dict(year=2024, position="★", topic=["不确定性量化", "分割"],
         title="Quantifying U-Net uncertainty in multi-parametric MRI-based glioma segmentation by spherical image projection",
         journal="Medical Physics", cite="2024;51(3):1931-1943",
         doi="10.1002/mp.16695", first_author="Yang Z",
         finding="SPU-Net：换不同球面投影中心得到多组预测，均值=分割结果、方差=不确定性图；369 例胶质瘤。",
         replicate="✅ 专栏 R2 / 页面「分割与不确定性」"),
    dict(year=2024, position="○", topic=["预后预测", "放疗剂量学"],
         title="Dose-Incorporated Deep Ensemble Learning for Improving Brain Metastasis Stereotactic Radiosurgery Outcome Prediction",
         journal="Int J Radiat Oncol Biol Phys", cite="2024;120(2):603-613",
         doi="10.1016/j.ijrobp.2024.04.006", first_author="Zhao J",
         finding="把实际剂量分布信息与影像、临床特征一起送进深度集成模型。",
         replicate="✅ 专栏 R6（剂量学特征的引入）"),
    dict(year=2024, position="☆", topic=["生存分析", "预后预测"],
         title="A dual-radiomics model for overall survival prediction in early-stage NSCLC patient using pre-treatment CT images",
         journal="Frontiers in Oncology", cite="2024;14:1419621",
         doi="10.3389/fonc.2024.1419621", first_author="Zhang R",
         finding="手工放射组学 + 深度放射组学双路建模预测总生存（TCIA Lung1 132 例）；特征重要性与模型预测能力高度相关。**他作为通讯作者的带学生成果。**",
         replicate="✅ 专栏 R5 / 页面「特征建模与预后」"),
    dict(year=2024, position="○", topic=["放射组学方法学"],
         title="Prognostic value of different discretization parameters in ¹⁸F-FDG PET radiomics of oropharyngeal squamous cell carcinoma",
         journal="Journal of Medical Imaging", cite="2024;11(2):024007",
         doi="10.1117/1.jmi.11.2.024007", first_author="Riley BA",
         finding="固定箱数 vs 固定箱宽（32/64/128/256 与 0.10–0.25）会改变预后结论；LASSO 逻辑回归 + 50 次蒙特卡洛交叉验证。",
         replicate="✅ 专栏 R1（binWidth 敏感性步骤）"),
    dict(year=2024, position="—", topic=["放疗剂量学"],
         title="国家自然科学基金青年科学基金项目：放疗中腹部图像自动分割的不确定性量化与评估研究",
         journal="国家自然科学基金（2024 年获批）", cite="DKU 当年共获 5 项",
         doi="", first_author="杨振宇（项目负责人）",
         finding="研究腹部图像自动分割中的不确定性量化与评估方法。",
         replicate="✅ 专栏 R2（不确定性范式的直接来源）"),
    dict(year=2025, position="★", topic=["放疗剂量学", "深度学习架构"],
         title="Total brain dose estimation in single-isocenter-multiple-targets (SIMT) radiosurgery via a novel deep neural network with spherical convolutions",
         journal="Medical Physics", cite="2025;52(6):4266-4277",
         doi="10.1002/mp.17748", first_author="Yang Z",
         finding="把脑「装进球里」做球面投影，用球面卷积（DeepSphere+HEALPix）预测 V50%/V60%/V66.7%；R²=0.92/0.94/0.93；参数量约 100 万，仅为 3D U-Net 的 1/30。",
         replicate="✅ 专栏 R3 / 页面「放疗剂量学工具」"),
    dict(year=2025, position="○", topic=["可解释AI", "影像基因组学"],
         title="Radiogenomic explainable AI with neural ordinary differential equation for identifying post-SRS brain metastasis radionecrosis",
         journal="Medical Physics", cite="2025;52(4):2661-2674",
         doi="10.1002/mp.17635", first_author="Zhao J",
         finding="HBNODE 把影像深度特征 + 基因组标志物 + 临床参数融合进潜空间，可视化每个病例走向诊断的轨迹。",
         replicate="—（Neural ODE 需训练；平台预留扩展位）"),
    dict(year=2025, position="☆", topic=["肺通气成像", "可解释AI"],
         title="An Explainable Neural Radiomic Sequence Model with Spatiotemporal Continuity for Quantifying 4DCT-based Pulmonary Ventilation",
         journal="arXiv 预印本", cite="arXiv:2503.23898（v2 2025-07-20）",
         doi="", first_author="Zhang R",
         finding="把静态 CT 升级为呼吸周期时间序列（56 维体素特征）；带时间显著性的 LSTM 判断通气缺陷，Dice 0.78/0.78、AUC 0.85/0.84，显著优于 U-Net 与 LSTM 基线。**结论：呼气相时受损区「强度上升、均匀性下降」。**",
         replicate="✅ 专栏 R1（特征图时序化思想的来源）"),
    dict(year=2025, position="○", topic=["不确定性量化", "分割"],
         title="Uncertainty quantification in multi-parametric MRI-based meningioma radiotherapy target segmentation",
         journal="Frontiers in Oncology", cite="2025;15:1474590",
         doi="10.3389/fonc.2025.1474590", first_author="Wang L",
         finding="把 SPU-Net 用于 76 例脑膜瘤，用信息熵量化不确定性、Otsu 聚合；Dice 0.760 vs U-Net 0.742，HD95 2.682 vs 2.912 cm。",
         replicate="✅ 专栏 R2（信息熵 + Otsu 聚合）"),
    dict(year=2025, position="○", topic=["图像配准", "深度学习架构"],
         title="An Implicit Registration Framework Integrating Kolmogorov–Arnold Networks with Velocity Regularization for Image-Guided Radiation Therapy",
         journal="Bioengineering", cite="2025;12(9):1005",
         doi="10.3390/bioengineering12091005", first_author="Sun P",
         finding="首次把 KAN（Jacobi 多项式构造）用于医学图像配准，对速度场主成分建模，效率提升约 70%。",
         replicate="✅ 专栏 R7（配准的物理约束思想）"),
    dict(year=2025, position="○", topic=["影像基因组学", "可解释AI"],
         title="A Radiogenomic Deep Ensemble Learning Model for Identifying Radionecrosis Following Brain Metastases SRS in Patients With Non-small Cell Lung Cancer BM",
         journal="Advances in Radiation Oncology", cite="2025;10:101826",
         doi="10.1016/j.adro.2025.101826", first_author="Zhao J",
         finding="90 个病灶/62 例；1024 维影像深度特征与临床（D+C）或基因组（D+G，EGFR/ALK/KRAS/PD-L1）用位置编码融合。",
         replicate="✅ 专栏 R4（多源融合）"),
    dict(year=2025, position="★", topic=["可解释AI"],
         title="揭开医学图像分析算法的黑箱：医学图像分析中可解释人工智能的最新进展",
         journal="科学通报（Chinese Science Bulletin）", cite="2025 年第 33 期",
         doi="10.1360/tb-2024-1299", first_author="杨振宇",
         finding="系统梳理 XAI 方法（显著性图、Grad-CAM/Score-CAM、LIME/SHAP、概念解释、因果与不确定性）在医学影像中的适用性与陷阱。**中文入门首选。**",
         replicate="✅ 平台「术语库」第 03 分册即据此整理"),
    dict(year=2025, position="★", topic=["放射组学方法学", "放疗剂量学"],
         title="A Dual Radiomic and Dosiomic Filtering Technique for Locoregional Radiation Pneumonitis Prediction in Breast Cancer Patients",
         journal="arXiv 预印本", cite="arXiv:2508.02169",
         doi="", first_author="Yang Z",
         finding="提出「双滤波」技术，把放射组学（影像）与剂量组学（剂量分布）联合用于局部区域放射性肺炎预测。",
         replicate="✅ 专栏 R6（剂量学 + 放射组学结合）"),
    dict(year=2026, position="★", topic=["不确定性量化", "分割"],
         title="A voxel-wise uncertainty-guided framework for glioma segmentation using spherical projection-based U-Net and localized refinement",
         journal="Medical Physics", cite="2026;53(3):e70360",
         doi="10.1002/mp.70360", first_author="Yang Z",
         finding="2D nnU-Net + 球面投影做初分割与不确定性量化 → 高不确定区交 3D nnU-Net 精修 → PSO 优化融合权重；BraTS 2020（369 例）全面超越 2D/3D 基线。",
         replicate="✅ 专栏 R2（不确定性引导的完整范式）"),
    dict(year=2026, position="★", topic=["深度学习架构", "放射组学方法学"],
         title="An exploratory study on integrating radiomics with vision transformers for enhancing medical imaging classification accuracy",
         journal="Medical Physics", cite="2026;53(1):e70246",
         doi="10.1002/mp.70246", first_author="Yang Z",
         finding="RE-ViT：把每个 patch 的手工放射组学特征与像素 embedding 平均后送进 ViT 编码器，用领域知识弥补 ViT 的数据饥渴。",
         replicate="—（需大数据与 GPU；平台在术语库解释其原理）"),
    dict(year=2026, position="☆", topic=["图像配准"],
         title="PhysMorph: A biomechanical and image-guided deep learning framework for real-time multi-modal liver image registration",
         journal="Physics and Imaging in Radiation Oncology", cite="2026;37:100906",
         doi="10.1016/j.phro.2026.100906", first_author="Zhang Z, Guo D",
         finding="有限元力学约束嵌入深度学习配准；TRE 2.2 mm、103.4 ms（传统 FEM >10 分钟）；代码开源。**他作为通讯作者。**",
         replicate="✅ 专栏 R7 / 页面「形变配准与物理合理性」"),
    dict(year=2026, position="○", topic=["可解释AI", "影像基因组学", "预后预测"],
         title="An Explainable Deep Model for Risk Scoring and Accurate Radionecrosis Identification Following Brain Metastasis Stereotactic Radiosurgery",
         journal="Int J Radiat Oncol Biol Phys", cite="2026;125(2):649-659",
         doi="10.1016/j.ijrobp.2025.11.038", first_author="Zhao J",
         finding="在 HBNODE 上加入 LRP（逐层相关性传播）量化非影像特征贡献，重构「决策场 F」并用 ∇F=0 的局部平衡点聚合中间状态。",
         replicate="—（数学最漂亮的一篇；平台预留扩展位）"),
    dict(year=2026, position="○", topic=["合成CT", "放疗剂量学"],
         title="Knowledge-based deep residual U-Net (DRU) for synthetic CT generation using a single MR volume for frameless radiosurgery",
         journal="J Appl Clin Med Phys", cite="2026;27(1):e70343",
         doi="10.1002/acm2.70343", first_author="Shu X",
         finding="用 DRU 从单次 MR 生成合成 CT，引入 Visible Human 解剖先验；PSNR 75±4 dB、SSIM 0.99；Gamma 通过率 95.8%（3%/1mm）。",
         replicate="✅ 专栏 R3（Gamma 指数验证步骤）"),
    dict(year=2026, position="☆", topic=["深度学习架构", "可解释AI"],
         title="Integrating Swin Transformers and Wavelet CNNs for Hierarchical Global–Local Mammographic Image Analysis",
         journal="IEEE Trans Radiat Plasma Med Sci", cite="2026",
         doi="10.1109/TRPMS.2026.3724585", first_author="Dai X",
         finding="Swin Transformer 抓全局形态、小波 CNN 抓局部纹理，组合成「全局—局部」分层架构用于乳腺影像。",
         replicate="—（需大数据；平台在术语库解释其原理）"),
]

# ----------------------------------------------------------------------
# 早期物理研究（本科期间，与东南大学侯吉旋老师合作）
# ----------------------------------------------------------------------
EARLY_PHYSICS = [
    dict(year=2019, title="Calculating the ground state energy of hydrogen molecules and helium hydride ions using Bohr's quantum theory",
         journal="European Journal of Physics", cite="40:065405", doi="10.1088/1361-6404/ab32ce"),
    dict(year=2019, title="Thermodynamic analysis of a long-range interacting spin system",
         journal="Modern Physics Letters B", cite="33:1950072", doi="10.1142/S0217984919500726"),
    dict(year=2019, title="Thermodynamic properties of a long-range interacting Bose system in staggered magnetic field",
         journal="European Physical Journal B", cite="92", doi="10.1140/epjb/e2019-100099-2"),
    dict(year=2020, title="Non-Markovian Mpemba effect in mean-field systems",
         journal="Physical Review E", cite="101:052106", doi="10.1103/PhysRevE.101.052106"),
    dict(year=2020, title="Shape transformation of red blood cells induced by the osmotic pressure",
         journal="European Journal of Physics", cite="41:065501", doi="10.1088/1361-6404/aba568"),
    dict(year=2022, title="Mpemba effect of a mean-field system: The phase transition time",
         journal="Physical Review E", cite="105:014119", doi="10.1103/PhysRevE.105.014119"),
]


def all_records() -> list[dict]:
    return PUBLICATIONS


def stats() -> dict:
    from collections import Counter
    years = Counter(p["year"] for p in PUBLICATIONS)
    positions = Counter(p["position"] for p in PUBLICATIONS)
    topics = Counter(t for p in PUBLICATIONS for t in p["topic"])
    return {
        "总数": len(PUBLICATIONS),
        "第一作者": positions.get("★", 0),
        "通讯/末位": positions.get("☆", 0),
        "合作者": positions.get("○", 0),
        "有复现": sum(1 for p in PUBLICATIONS if p["replicate"].startswith("✅")),
        "按年份": dict(sorted(years.items())),
        "按主题": dict(topics.most_common()),
        "按位次": dict(positions),
    }
